const images = {
  fbletter: require("../../assets/fb_letter.png"),
  gpletter: require("../../assets/google_letter.png"),
  username: require("../../assets/username.png"),
  password: require("../../assets/key.png"),
  linkdin: require("../../assets/linkdin.png"),
  home: require("../../assets/homeIconNew.png"),
  homeIcon: require("../../assets/home.png"),
  record: require("../../assets/record.png"),
  check: require("../../assets/check.png"),
  cross: require("../../assets/cross.png"),
  profile: require("../../assets/account.png"),
  email: require("../../assets/mail.png"),
  phone: require("../../assets/phone.png"),
  time: require("../../assets/time.png"),
  url: require("../../assets/url.png"),
  title: require("../../assets/title.png"),
  header: require("../../assets/MyHeader.png"),
  clickRadio: require("../../assets/clickRadio.png"),
  // mainPic: require("../../assets/mainPic.png"),
  searchIcon: require("../../assets/searchIconNew.png"),
  travel: require("../../assets/travel.png"),
  currentLocation: require("../../assets/currentLocation.png"),
  // resturant: require("../../assets/resturant.png"),
  rating: require("../../assets/rating.png"),
  male: require("../../assets/male.png"),
  female: require("../../assets/female.png"),
  location: require("../../assets/location.png"),
  success: require("../../assets/success.png"),
  leftarrow: require("../../assets/leftarrow.png"),
  cleaning: require("../../assets/cleaning.png"),
  sanitizer: require("../../assets/sanitizer.png"),
  mask: require("../../assets/mask.png"),
  distancing: require("../../assets/distancing.png"),
  selfcheckout: require("../../assets/selfcheckout.png"),
  signUp: require("../../assets/signup-e.png"),
  mask_blue: require("../../assets/mask-blue.png"),
  survey: require("../../assets/survey.5.png"),
  single_survey: require("../../assets/single-star.png"),
  single_survey_left: require("../../assets/single-star-left.png"),
  single_survey_right: require("../../assets/single-star-right.png"),
  single_survey_right_heart: require("../../assets/single-star-right-heart.png"),
  single_survey_left_heart: require("../../assets/single-star-left-heart.png"),
  verification: require("../../assets/verification.png"),
  persons: require("../../assets/persons.png"),
  mast_theme: require("../../assets/mask-theme.png"),
  spa: require("../../assets/spa-1.png"),
  checkout: require("../../assets/checkout.png"),
  hand: require("../../assets/hand.png"),
  avatar: require("../../assets/dp.png"),
  markDestination: require("../../assets/markDestination.png"),
  // avatarDP: require("../../assets/Group.png"),
  review: require("../../assets/myreviewsNew.png"),
  // reviewTest: require("../../assets/testReview.jpg"),
  corona: require("../../assets/Page-1.png"),
  myBusiness: require("../../assets/mybusinessNew.png"),
  marker: require("../../assets/makerIcon.png"),
  blueRest: require('../../assets/blueRest.png'),
  redRest: require('../../assets/redRest.png'),
  placeHolder: require('../../assets/placeholder.png'),
  customerService: require('../../assets/customer-service.png'),
  // avatar : require('../../assets/Group10470.png'),

  close: require('../../assets/icn_close.png'),
  setting: require('../../assets/Icon-feather-settings.png'),
  logout: require('../../assets/Icon-open-account-logout.png'),
  drawerMenu: require('../../assets/drawerMenu.png'),
  fullDrawerMenu: require('../../assets/fullDrawerMenu.png'),

  privayPolicy: require('../../assets/privacy-policy.png'),

};
export default images;
