const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";

const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

const VERIFY_FORGOT_PASS_REQUEST = "VERIFY_FORGOT_PASS_REQUEST";
const VERIFY_FORGOT_PASS_SUCCESS = "VERIFY_FORGOT_PASS_SUCCESS";
const VERIFY_FORGOT_PASS_FAILURE = "VERIFY_FORGOT_PASS_FAILURE";


const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";
const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
const VERIFY_EMAIL_FAILURE = "VERIFY_EMAIL_FAILURE";
const LOGOUT = "LOGOUT";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";


export const types = {

    REGISTRATION_REQUEST,
    REGISTRATION_SUCCESS,
    REGISTRATION_FAILURE,
  
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
  
    RESET_PASSWORD_REQUEST,
    RESET_PASSWORD_SUCCESS,
    RESET_PASSWORD_FAILURE,
  
    FORGOT_PASSWORD_REQUEST,
    FORGOT_PASSWORD_SUCCESS,
    FORGOT_PASSWORD_FAILURE,
  
    VERIFY_FORGOT_PASS_REQUEST,
    VERIFY_FORGOT_PASS_SUCCESS,
    VERIFY_FORGOT_PASS_FAILURE,

    VERIFY_EMAIL_REQUEST,
    VERIFY_EMAIL_SUCCESS,
    VERIFY_EMAIL_FAILURE,
    
    LOGOUT,
    LOGOUT_SUCCESS,
}