const ADD_SET_REQUEST = "ADD_SET_REQUEST";
const ADD_SET_SUCCESS = "ADD_SET_SUCCESS";
const ADD_SET_FAILURE = "ADD_SET_FAILURE";

const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

const GET_USER_REQUEST = "GET_USER_REQUEST";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_FAILURE = "GET_USER_FAILURE";

const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

const FINISH_TRIP_REQUEST = "FINISH_TRIP_REQUEST";
const FINISH_TRIP_SUCCESS = "FINISH_TRIP_SUCCESS";
const FINISH_TRIP_FAILURE = "FINISH_TRIP_FAILURE";

const MY_TRIPS_REQUEST = "MY_TRIPS_REQUEST";
const MY_TRIPS_SUCCESS = "MY_TRIPS_SUCCESS";
const MY_TRIPS_FAILURE = "MY_TRIPS_FAILURE";

const DELETE_TRIP_REQUEST = "DELETE_TRIP_REQUEST";
const DELETE_TRIP_SUCCESS = "DELETE_TRIP_SUCCESS";
const DELETE_TRIP_FAILURE = "DELETE_TRIP_FAILURE";

const REMOVE_USER_DATA = "REMOVE_USER_DATA";

export const types = {

  ADD_SET_REQUEST,
  ADD_SET_SUCCESS,
  ADD_SET_FAILURE,
  
  UPDATE_PROFILE_REQUEST,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_FAILURE,
  
  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,
  
  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILURE,

  FINISH_TRIP_REQUEST,
  FINISH_TRIP_SUCCESS,
  FINISH_TRIP_FAILURE,

  MY_TRIPS_REQUEST,
  MY_TRIPS_SUCCESS,
  MY_TRIPS_FAILURE,

  DELETE_TRIP_REQUEST,
  DELETE_TRIP_SUCCESS,
  DELETE_TRIP_FAILURE,

  REMOVE_USER_DATA,
};