const UPDATE_BUSINESS_REQUEST = "UPDATE_BUSINESS_REQUEST";
const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
const UPDATE_BUSINESS_FAILURE = "UPDATE_BUSINESS_FAILURE";

const CLAIM_BUSINESS_REQUEST = "CLAIM_BUSINESS_REQUEST";
const CLAIM_BUSINESS_SUCCESS = "CLAIM_BUSINESS_SUCCESS";
const CLAIM_BUSINESS_FAILURE = "CLAIM_BUSINESS_FAILURE";

const VERIFY_PHONE_REQUEST = "VERIFY_PHONE_REQUEST";
const VERIFY_PHONE_SUCCESS = "VERIFY_PHONE_SUCCESS";
const VERIFY_PHONE_FAILURE = "VERIFY_PHONE_FAILURE";

const SEARCH_FIELD_BUSINESS_REQUEST = "SEARCH_FIELD_BUSINESS_REQUEST";
const SEARCH_FIELD_BUSINESS_SUCCESS = "SEARCH_FIELD_BUSINESS_SUCCESS";
const SEARCH_FIELD_BUSINESS_FAILURE = "SEARCH_FIELD_BUSINESS_FAILURE";

const SINGLE_BUSINESS_REQUEST = "SINGLE_BUSINESS_REQUEST";
const SINGLE_BUSINESS_SUCCESS = "SINGLE_BUSINESS_SUCCESS";
const SINGLE_BUSINESS_FAILURE = "SINGLE_BUSINESS_FAILURE";

const UPDATE_OWNERBUSINESS_REQUEST = "UPDATE_OWNERBUSINESS_REQUEST";
const UPDATE_OWNERBUSINESS_SUCCESS = "UPDATE_OWNERBUSINESS_SUCCESS";
const UPDATE_OWNERBUSINESS_FAILURE = "UPDATE_OWNERBUSINESS_FAILURE";

const SAVE_RATING_REQUEST = "SAVE_RATING_REQUEST";
const SAVE_RATING_SUCCESS = "SAVE_RATING_SUCCESS";
const SAVE_RATING_FAILURE = "SAVE_RATING_FAILURE";

const SAVE_FEEDBACK_REQUEST = "SAVE_FEEDBACK_REQUEST";
const SAVE_FEEDBACK_SUCCESS = "SAVE_FEEDBACK_SUCCESS";
const SAVE_FEEDBACK_FAILURE = "SAVE_FEEDBACK_FAILURE";

const SEARCH_BUSINESS_REQUEST = "SEARCH_BUSINESS_REQUEST";
const SEARCH_BUSINESS_SUCCESS = "SEARCH_BUSINESS_SUCCESS";
const SEARCH_BUSINESS_FAILURE = "SEARCH_BUSINESS_FAILURE";

const TRIP_NEXT_PAGE = "TRIP_NEXT_PAGE";

export const types = {
  UPDATE_OWNERBUSINESS_REQUEST,
  UPDATE_OWNERBUSINESS_SUCCESS,
  UPDATE_OWNERBUSINESS_FAILURE,

  SINGLE_BUSINESS_REQUEST,
  SINGLE_BUSINESS_FAILURE,
  SINGLE_BUSINESS_SUCCESS,

  SEARCH_FIELD_BUSINESS_REQUEST,
  SEARCH_FIELD_BUSINESS_FAILURE,
  SEARCH_FIELD_BUSINESS_SUCCESS,

  CLAIM_BUSINESS_REQUEST,
  CLAIM_BUSINESS_SUCCESS,
  CLAIM_BUSINESS_FAILURE,

  UPDATE_BUSINESS_REQUEST,
  UPDATE_BUSINESS_SUCCESS,
  UPDATE_BUSINESS_FAILURE,

  VERIFY_PHONE_REQUEST,
  VERIFY_PHONE_SUCCESS,
  VERIFY_PHONE_FAILURE,

  SAVE_RATING_REQUEST,
  SAVE_RATING_SUCCESS,
  SAVE_RATING_FAILURE,

  SAVE_FEEDBACK_REQUEST,
  SAVE_FEEDBACK_SUCCESS,
  SAVE_FEEDBACK_FAILURE,

  SEARCH_BUSINESS_REQUEST,
  SEARCH_BUSINESS_SUCCESS,
  SEARCH_BUSINESS_FAILURE,

  TRIP_NEXT_PAGE,
};
